import { useSelector } from 'react-redux';
import { useDispatch } from 'react-redux';

import { uiActions } from '../store/ui-slice';
import classes from './CartButton.module.css';

const CartButton = (props) => {
  const dispatch = useDispatch();
  const cartQuantity = useSelector(state => state.cart.totalQuantity);

  const toggleCartHandler = () => {
    dispatch(uiActions.toggle());  //this autogenerated action (action creator methods) return an object which we dispatch here
  };

  //IN SHORT STORE MATHI COMPONENETS MA ACTION DISPATCH KARI

  return (
    <button className={classes.button} onClick={toggleCartHandler}>
      <span>My Cart</span>
      <span className={classes.badge}>{cartQuantity}</span>
    </button>
  );
};

export default CartButton;
